---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-deployment
  namespace: my-cool-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fastapi-app
  template:
    metadata:
      labels:
        app: fastapi-app
    spec:
      nodeSelector:
        workload-type: developers-workshop
      tolerations:
      - key: workload-type
        value: developers-workshop
        effect: NoSchedule
        operator: Equal
      containers:
      - name: web
        image: 012345678901.dkr.ecr.us-west-2.amazonaws.com/fastapi-microservices:1.0
        ports:
        - containerPort: 8000
        envFrom:
        - secretRef:
            name: fastapi-secret
        resources:
          requests:
            cpu: "200m"
            memory: "200Mi"
